# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'T100Scanner' do
pod 'CocoaAsyncSocket'
end

target 'T100ScannerTests' do

end

target 'T100ScannerUITests' do

end

